version: '3.8'

services:
  postgres:
    container_name: pgdbSptingStudy
    image: postgres
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./db/pg/data/:/var/lib/postgresql/data
    ports:
      - "5432:5432"